name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Clean problematic files
      run: |
        rm -rf .buildozer .gitmodules
    
    - name: Build with Buildozer Action
      uses: ArtemSBulgakov/buildozer-action@v1
      with:
        command: buildozer android debug
        buildozer_version: master
      env:
        ANDROID_API_LEVEL: 34
        ANDROID_BUILD_TOOLS_VERSION: 34.0.0
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: bin/*.apk
